name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
      working-directory: ./ARProject/ARProject-API
    - name: Build API Project
      run: dotnet build ARProject-API.csproj --no-restore
      working-directory: ./ARProject/ARProject-API
    - name: Run API Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: ./ARProject/ARProject-API
    - name: Docker build
      run: docker build -f "./ARProject/ARProject-API/Dockerfile" --force-rm -t "containerregistryarprojectdev.azurecr.io/arprojectapi:latest" --target base "./ARProject"
    - name: Docker login
      run: docker login containerregistryarprojectdev.azurecr.io -u ${{ secrets.DOCKER_USER }} -p erqsVzH7A58n/Es10QAuDc2TBfnA5H8L
    - name: Docker push
      run: docker push "containerregistryarprojectdev.azurecr.io/arprojectapi:latest"