name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore Dependencies
      run: dotnet restore
      working-directory: ./ARProject/ARProject-API
    - name: List Folder
      run: ls -la
      working-directory: ./ARProject/ARProject-API
    - name: Build API Project
      run: dotnet build ARProject-API.csproj --no-restore
      working-directory: ./ARProject/ARProject-API
    - name: Run API Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: ./ARProject/ARProject-API
    - name: Make dockerout folder
      run: mkdir dockerout
      working-directory: ./ARProject/ARProject-API
    - uses: azure/docker-login@v1
      with:
        login-server: 'containerregistryarprojectdev.azurecr.io'
        username: 'containerregistrydevarproject'
        password: '=d/cPpwE/lUHnpqt=PDYW1AsnoMKDRG7'
    - name: Docker build
      run: docker build -f "Dockerfile" --force-rm -t arprojectapi:dev --target base --label "com.microsoft.visual-studio.project-name=ARProject-API" "./dockerout"
      working-directory: ./ARProject/ARProject-API
    - name: Docker push
      run: docker push containerregistryarprojectdev.azurecr.io/arprojectapi:${{ github.sha }}
      working-directory: ./ARProject/ARProject-API