name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./ARProject/ARProject-API
    - name: List
      run: ls -la
    - name: Build
      run: dotnet build ARProject-API.csproj --no-restore
      working-directory: ./ARProject/ARProject-API
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./ARProject/ARProject-API
    - name: Mkdir
      run: mkdir dockerout
      working-directory: ./ARProject/ARProject-API
    - name: Docker build
      run: docker build -f "Dockerfile" --force-rm -t arprojectapi:dev --target base --label "com.microsoft.created-by=visual-studio" --label "com.microsoft.visual-studio.project-name=ARProject-API" "./dockerout"
      working-directory: ./ARProject/ARProject-API
    - name: ListDocker
      run: ls -la
      working-directory: ./ARProject/ARProject-API/dockerout